services:
  database:
    image: mysql:9.3
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - login_database_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - login_network

  backendvuln:
    build:
      context: .
      dockerfile: ./packages/backendvuln/Dockerfile
    environment:
      - DB_HOST=database
      - DB_NAME=loginvuln
      - DB_USER=root
      - DB_PASS=root
    ports:
      - 8080:8080
    networks:
      - login_network

  backend:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    environment:
      - CSRF_SECRET=12kjh4kjh5kjg356jhg7hgf8hg9cfgjh
      - DB_HOST=database
      - DB_NAME=loginrein
      - DB_USER=root
      - DB_PASS=root
    ports:
      - 8081:8081
    networks:
      - login_network


volumes:
  login_database_data:


networks:
  login_network:
